{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoError","stack":"MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (/Users/chienhunglin/Dropbox/chatbot/botbuilder-line-connector/node_modules/mongodb-core/lib/topologies/server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/Users/chienhunglin/Dropbox/chatbot/botbuilder-line-connector/node_modules/mongodb-core/lib/connection/pool.js:260:12)\n    at Connection.g (events.js:291:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/Users/chienhunglin/Dropbox/chatbot/botbuilder-line-connector/node_modules/mongodb-core/lib/connection/connection.js:162:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)","level":"warn","timestamp":"2016-12-01T12:15:47.513Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoError","stack":"MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (/Users/chienhunglin/Dropbox/chatbot/botbuilder-line-connector/node_modules/mongodb-core/lib/topologies/server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/Users/chienhunglin/Dropbox/chatbot/botbuilder-line-connector/node_modules/mongodb-core/lib/connection/pool.js:260:12)\n    at Connection.g (events.js:291:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/Users/chienhunglin/Dropbox/chatbot/botbuilder-line-connector/node_modules/mongodb-core/lib/connection/connection.js:162:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)","level":"warn","timestamp":"2016-12-01T12:15:47.517Z"}
